language: node_js
node_js:
  - "8"
addons:
  chrome: stable
sudo: required
install:
  - npm install
before_install:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
